### ISSUE TITLE
the bug of the eval.py

### ISSUE THREAD

**Issue by five-days** [hqucv/siamban#23]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "F:\anaconda\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\lTtracking\siamban-master\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "D:\lTtracking\siamban-master\toolkit\utils\statistics.py", line 105, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array
"""

**Comment by zeduchen** [comment]
Please check if the input is correct, such as ground-truth.
