### ISSUE TITLE
eval error

### ISSUE THREAD

**Issue by XiaoBai-collab** [hqucv/siamban#31]
An error occured when i ran the  eval  file:
loading OTB100: 100%|█████████████████████████████████████| 100/100 [00:00<00:00, 277.96it/s, Woman]
Traceback (most recent call last):
  File "eval.py", line 148, in <module>
    main()
  File "eval.py", line 52, in main
    with Pool(processes=args.num) as pool:
  File "/home/xiaobai/anaconda3/envs/torch/lib/python3.6/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/xiaobai/anaconda3/envs/torch/lib/python3.6/multiprocessing/pool.py", line 167, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

So how can i solve this problem? Thanks a lot.

**Comment by zeduchen** [comment]
The parameter `--num` in eval.py is set to at least 1.

**Comment by XiaoBai-collab** [comment]
> The parameter `--num` in eval.py is set to at least 1.

Thanks for your reply! I have solved this problem.
