### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Tangzhaotz** [hqucv/siamban#41]
raise KeyError(key) from None
KeyError: 'RANK'

**Comment by zeduchen** [comment]
Can you provide a more detailed description and experiment log?

**Comment by Tangzhaotz** [comment]
Traceback (most recent call last):
  File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 310, in <module>
    main()
  File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 249, in main
    rank, world_size = dist_init()
  File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 104, in dist_init
    rank, world_size = _dist_init()
  File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 83, in _dist_init
    rank = int(os.environ['RANK'])
  File "/home/tz/.conda/envs/siamban/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by zeduchen** [comment]
Do you run the code directly in the IDE? We run the code in the Linux terminal.

**Comment by FMZCY** [comment]
> Do you run the code directly in the IDE? We run the code in the Linux terminal.

I run the code in the Linux terminal,but I still have the same problem...

**Comment by FMZCY** [comment]
> Traceback (most recent call last): File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 310, in main() File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 249, in main rank, world_size = dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 104, in dist_init rank, world_size = _dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 83, in _dist_init rank = int(os.environ['RANK']) File "/home/tz/.conda/envs/siamban/lib/python3.7/os.py", line 681, in **getitem** raise KeyError(key) from None KeyError: 'RANK'

Have you solved the problem yet?If so, could you please tell me the solution....

**Comment by 894986710** [comment]
> > Traceback (most recent call last): File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 310, in main() File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 249, in main rank, world_size = dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 104, in dist_init rank, world_size = _dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 83, in _dist_init rank = int(os.environ['RANK']) File "/home/tz/.conda/envs/siamban/lib/python3.7/os.py", line 681, in **getitem** raise KeyError(key) from None KeyError: 'RANK'
> 
> Have you solved the problem yet?If so, could you please tell me the solution....

**Comment by 894986710** [comment]
> > Traceback (most recent call last): File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 310, in main() File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 249, in main rank, world_size = dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 104, in dist_init rank, world_size = _dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 83, in _dist_init rank = int(os.environ['RANK']) File "/home/tz/.conda/envs/siamban/lib/python3.7/os.py", line 681, in **getitem** raise KeyError(key) from None KeyError: 'RANK'
> 
> Have you solved the problem yet?If so, could you please tell me the solution....
兄弟你解决这个问题了么

**Comment by xiaobai111111223** [comment]
遇到了相同的问题，求教怎样解决

**Comment by xiaobai111111223** [comment]
> > Do you run the code directly in the IDE? We run the code in the Linux terminal.
> 
> I run the code in the Linux terminal,but I still have the same problem...

您好，这个问题您解决了吗？怎样解决的可以说一下吗

**Comment by xiaobai111111223** [comment]
> > > Traceback (most recent call last): File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 310, in main() File "/home/tz/code_siamban/siamban_源码/tools/train.py", line 249, in main rank, world_size = dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 104, in dist_init rank, world_size = _dist_init() File "/home/tz/code_siamban/siamban_源码/siamban/utils/distributed.py", line 83, in _dist_init rank = int(os.environ['RANK']) File "/home/tz/.conda/envs/siamban/lib/python3.7/os.py", line 681, in **getitem** raise KeyError(key) from None KeyError: 'RANK'
> > 
> > 
> > Have you solved the problem yet?If so, could you please tell me the solution....
> > 兄弟你解决这个问题了么

您好，这个问题您解决了吗
