### ISSUE TITLE
can not train

### ISSUE THREAD

**Issue by huiby23** [hqucv/siamban#48]
subprocess.CalledProcessError: Command '['/home/hhh/.conda/envs/siamban/bin/python', '-u', './tools/train.py', '--local_rank=1', '--cfg', 'experiments/siamban_r50_l234/config.yaml']' returned non-zero exit status 1.

**Comment by zeduchen** [comment]
Hi, can you provide more information?

**Comment by wyq2020022029** [comment]
Excuse me, have you solved your problem

**Comment by ZhangShiAo** [comment]
> 对不起，你解决了你的问题吗

请问你解决这个了吗

**Comment by turingvideosjp** [comment]
you should change your port 2333 to other

**Comment by long-wa** [comment]
i also encounter this problem, such as this :
(siamban1) root@node02:~/data/zjx/siamBAN/siamban_ori/experiments/siamban_r50_l234# python -m torch.distributed.launch     --nproc_per_node=3     --master_port=2333     ../../tools/train.py --cfg config.yaml
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "../../tools/train.py", line 31, in <module>
    from siamban.datasets.dataset import BANDataset
  File "/root/data/zjx/siamBAN/siamban_ori/siamban/datasets/dataset.py", line 13, in <module>
    import cv2
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    Traceback (most recent call last):
bootstrap()
  File "../../tools/train.py", line 31, in <module>
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/root/anaconda3/envs/siamban1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    from siamban.datasets.dataset import BANDataset
  File "/root/data/zjx/siamBAN/siamban_ori/siamban/datasets/dataset.py", line 13, in <module>
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
    import cv2
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/root/anaconda3/envs/siamban1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "../../tools/train.py", line 31, in <module>
    from siamban.datasets.dataset import BANDataset
  File "/root/data/zjx/siamBAN/siamban_ori/siamban/datasets/dataset.py", line 13, in <module>
    import cv2
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/root/anaconda3/envs/siamban1/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/root/anaconda3/envs/siamban1/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/siamban1/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/root/anaconda3/envs/siamban1/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/root/anaconda3/envs/siamban1/bin/python', '-u', '../../tools/train.py', '--local_rank=2', '--cfg', 'config.yaml']' returned non-zero exit status 1.
