### ISSUE TITLE
Some problems in testing!

### ISSUE THREAD

**Issue by prstrive** [hqucv/siamban#55]
Hello! When I test the model, I get this error message:
```
Traceback (most recent call last):
  File "../../tools/test.py", line 21, in <module>
    from toolkit.utils.region import vot_overlap, vot_float2str
  File "/data/pengr/pysot/toolkit/utils/__init__.py", line 1, in <module>
    from . import region
ImportError: cannot import name 'region'
```
What should I do?

**Comment by prstrive** [comment]
solved
