### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by Standdrinkmilk** [hqucv/siamban#62]
hello，I have a problem. I downloaded the vid , but it couldn't find the data during training....
can you help solve the problem？

Traceback (most recent call last):
  File "../../tools/train.py", line 309, in <module>
    main()
  File "../../tools/train.py", line 304, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 167, in train
    for idx, data in enumerate(train_loader):
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/kong/lv1/Code/siamban-master/siamban/datasets/dataset.py", line 253, in __getitem__
    template_box = self._get_bbox(template_image, template[1])
  File "/media/kong/lv1/Code/siamban-master/siamban/datasets/dataset.py", line 214, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Traceback (most recent call last):
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/kong/anaconda3/envs/siamban/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/kong/anaconda3/envs/siamban/bin/python', '-u', '../../tools/train.py', '--local_rank=0', '--cfg', 'config.yaml']' returned non-zero exit status 1.

**Comment by LearnByDoingXW** [comment]
我也遇到了相同的问题，是暑假回来之后突然这样的，其他数据集都没有问题，只有lasot出现了这样的问题。我重新处理了数据集或者只用数据集的一部分都没能解决问题，网上一部分人说是环境的问题，我还没有尝试，希望尽快解决这个问题。
